### ISSUE TITLE
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/typescript-map

### ISSUE THREAD

**Issue by QuarK264** [ClickSimply/typescript-map#1]
I install package this way https://www.npmjs.com/package/typescript-map. When I try to use it i get error:

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/typescript-map
	Error: XHR error (404 Not Found) loading http://localhost:3000/typescript-map
	    at XMLHttpRequest.wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17)
	Error loading http://localhost:3000/typescript-map as "typescript-map" from http://localhost:3000/app/time.component.js
	    at XMLHttpRequest.wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17)
	Error loading http://localhost:3000/typescript-map as "typescript-map" from http://localhost:3000/app/time.component.js

**Comment by only-cliches** [comment]
Looks like you're using Angular, what's your import statement look like?

**Comment by QuarK264** [comment]
Yes, I use it. I use this statement "import { TSMap } from "typescript-map"". I also tried this "import { TSMap } from "./typescript-map"", result was the same.

**Comment by only-cliches** [comment]
Doing some digging, it looks like you need to configure your system.config.js file.

I have no experience with Angular and the system.config.js file, but I did some research and **_I think_** you need to add this entry to the "map" object in system.config.js

```js
map: {
    "typescript-map": "npm:typescript-map",
    ....
}
```

Another thing you could try is adjusting your import statement like below:
```es6
import { TSMap } from "npm:typescript-map";
```

Since this is an issue not related to Typescript Map but SystemJS I'm going to mark it as resolved.  If the solution above doesn't work you should look into how to support NPM packages with SystemJS.
